[2022-11-06 17:45:39,038][django.security.DisallowedHost.response_for_exception():75] [ERROR] Invalid HTTP_HOST header: 'api.educationcity.cn:8000'. You may need to add 'api.educationcity.cn' to ALLOWED_HOSTS.
[2022-11-06 17:45:39,371][django.security.DisallowedHost.response_for_exception():75] [ERROR] Invalid HTTP_HOST header: 'api.educationcity.cn:8000'. You may need to add 'api.educationcity.cn' to ALLOWED_HOSTS.
[2022-11-07 02:32:01,893][django.security.DisallowedHost.response_for_exception():75] [ERROR] Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
[2022-11-07 02:32:02,620][django.security.DisallowedHost.response_for_exception():75] [ERROR] Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
[2022-11-07 03:35:45,952][django.request.log_response():222] [ERROR] Internal Server Error: /banner/
Traceback (most recent call last):
  File "/home/noel/anaconda3/envs/p_education/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/noel/anaconda3/envs/p_education/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/noel/anaconda3/envs/p_education/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/noel/anaconda3/envs/p_education/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/noel/anaconda3/envs/p_education/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/noel/anaconda3/envs/p_education/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/noel/anaconda3/envs/p_education/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/noel/anaconda3/envs/p_education/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/noel/anaconda3/envs/p_education/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/noel/anaconda3/envs/p_education/lib/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/home/noel/anaconda3/envs/p_education/lib/python3.8/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/noel/anaconda3/envs/p_education/lib/python3.8/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'ListAPIView' should either include a `queryset` attribute, or override the `get_queryset()` method.
[2022-11-07 03:35:45,955][django.server.log_message():154] [ERROR] "GET /banner/ HTTP/1.1" 500 110332
